tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 0.1
      
micronaut:
  router:
        static-resources:
            swagger: {paths: 'classpath:META-INF/swagger', mapping: '/swagger/**'}
            swagger-ui: {paths: 'classpath:META-INF/swagger/views/swagger-ui', mapping: '/swagger-ui/**'}  
  server:
    port: 8081
mongodb:
  uri: set_the_mongoDB_URL

app:
  mongodb:
    db:
      name: deliverymoment-evl-db
      collection:
        deliveryMoment: delivery-moment​
        sequences: counters

endpoints:
  metrics:
    enabled: true
    sensitive: false
  health:
    enabled: true
    details-visible: ANONYMOUS
  env:
    enabled: true
    sensitive: false
    